export const AFTER_SALES_RETURN_WINDOW_DAYS = 7;

export const AFTER_SALES_PAGINATION = {
    FIRST_PAGE: 1,
    MIN_PAGE_SIZE: 1,
    DEFAULT_PAGE_SIZE: 50,
    MAX_PAGE_SIZE: 100,
} as const;

export const AFTER_SALES_VALIDATION_LIMITS = {
    ITEM_QUANTITY: 99,
    ITEM_REASON_LENGTH: 500,
    REQUEST_REASON_LENGTH: 5_000,
    ITEMS_PER_REQUEST: 50,
    IDEMPOTENCY_KEY_LENGTH: 128,
    GUEST_ORDER_TOKEN_LENGTH: 256,
    REFUND_REFERENCE_LENGTH: 255,
    CURRENCY_CODE_LENGTH: 3,
    NOTE_LENGTH: 5_000,
} as const;
