packages:
  - "client"
  - "server"
allowBuilds:
  '@firebase/util': false
  '@parcel/watcher': false
  esbuild: false
  geckodriver: false
  msw: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
